<TABLE WIDTH="120" BORDER="0" CELLSPACING="0" CELLPADDING="0" DWCOPYTYPE="CopyTableRow">
                          <TR> 
                            <TD HEIGHT="30">&nbsp;</TD>
                          </TR>
                          <TR BGCOLOR="#FFFFFF"> 
                            <TD><IMG SRC="../img/general/spacer.gif" WIDTH="1" HEIGHT="1"></TD>
                          </TR>
                          <TR> 
                            <TD>
                              <TABLE WIDTH="120" BORDER="0" CELLSPACING="0" CELLPADDING="0">
                                <TR>
                                  <TD WIDTH="24" BGCOLOR="#6D99A7" ALIGN="center"><IMG SRC="../img/general/noticias/news_icon.gif" WIDTH="21" HEIGHT="25"></TD>
                                  <TD BGCOLOR="#FFFFFF" WIDTH="1"><IMG SRC="../img/general/spacer.gif" WIDTH="1" HEIGHT="1"></TD>
                                  
                      
          <TD WIDTH="95" BGCOLOR="#6D99A7">&nbsp;<A HREF="<? echo $PHP_SELF ?>?inc=mas&tipo=<? echo $tipo ?>" >&gt; 
            m&aacute;s <? echo $tipo ?>s</A> </TD>
                                </TR>
                              </TABLE>
                              <TABLE WIDTH="120" BORDER="0" CELLSPACING="0" CELLPADDING="0">
                                <TR BGCOLOR="#FFFFFF"> 
                                  <TD HEIGHT="1"><IMG SRC="../img/general/spacer.gif" WIDTH="1" HEIGHT="1"></TD>
                                </TR>
                              </TABLE>
                              <TABLE WIDTH="120" BORDER="0" CELLSPACING="0" CELLPADDING="0">
                                <TR> 
                                  <TD WIDTH="24" BGCOLOR="#6D99A7"><IMG SRC="../img/general/noticias/print_icon.gif" WIDTH="24" HEIGHT="24" VSPACE="1"></TD>
                                  <TD BGCOLOR="#FFFFFF" WIDTH="1"><IMG SRC="../img/general/spacer.gif" WIDTH="1" HEIGHT="1"></TD>
                                  
                      <TD WIDTH="95" BGCOLOR="#6D99A7">&nbsp;<A HREF="javascript:openwin('../include/print.html?id=<? echo $noticia[id] ?>&tipo=noticia','print','width=335,height=350,scrollbars=1')">&gt; 
                        imprimir</A></TD>
                                </TR>
                              </TABLE>
                              <TABLE WIDTH="120" BORDER="0" CELLSPACING="0" CELLPADDING="0">
                                <TR BGCOLOR="#FFFFFF"> 
                                  <TD HEIGHT="1"><IMG SRC="../img/general/spacer.gif" WIDTH="1" HEIGHT="1"></TD>
                                </TR>
                              </TABLE>
                              <TABLE WIDTH="120" BORDER="0" CELLSPACING="0" CELLPADDING="0">
                                <TR> 
                                  <TD WIDTH="24" BGCOLOR="#6D99A7"><IMG SRC="../img/general/noticias/recomienda_ico.gif" WIDTH="24" HEIGHT="19" VSPACE="2"></TD>
                                  <TD BGCOLOR="#FFFFFF" WIDTH="1"><IMG SRC="../img/general/spacer.gif" WIDTH="1" HEIGHT="1"></TD>
                                  
                      <TD WIDTH="95" BGCOLOR="#6D99A7">&nbsp;<A HREF="javascript:openwin('../include/enviar.html?id=<? echo $noticia[id] ?>&tipo=noticia','enviar','width=400,height=220,scrollbars=0')">&gt; 
                        enviar</A></TD>
                                </TR>
                              </TABLE>
                            </TD>
                          </TR>
  <TR BGCOLOR="#FFFFFF"> 
    <TD><IMG SRC="../img/general/spacer.gif" WIDTH="1" HEIGHT="1"></TD>
  </TR>

                        </TABLE>