<HTML>
<SCRIPT LANGUAGE="JavaScript">
<!--
function MM_swapImgRestore() { //v3.0
  var i,x,a=document.MM_sr; for(i=0;a&&i<a.length&&(x=a[i])&&x.oSrc;i++) x.src=x.oSrc;
}

function MM_preloadImages() { //v3.0
  var d=document; if(d.images){ if(!d.MM_p) d.MM_p=new Array();
    var i,j=d.MM_p.length,a=MM_preloadImages.arguments; for(i=0; i<a.length; i++)
    if (a[i].indexOf("#")!=0){ d.MM_p[j]=new Image; d.MM_p[j++].src=a[i];}}
}

function MM_findObj(n, d) { //v3.0
  var p,i,x;  if(!d) d=document; if((p=n.indexOf("?"))>0&&parent.frames.length) {
    d=parent.frames[n.substring(p+1)].document; n=n.substring(0,p);}
  if(!(x=d[n])&&d.all) x=d.all[n]; for (i=0;!x&&i<d.forms.length;i++) x=d.forms[i][n];
  for(i=0;!x&&d.layers&&i<d.layers.length;i++) x=MM_findObj(n,d.layers[i].document); return x;
}

function MM_swapImage() { //v3.0
  var i,j=0,x,a=MM_swapImage.arguments; document.MM_sr=new Array; for(i=0;i<(a.length-2);i+=3)
   if ((x=MM_findObj(a[i]))!=null){document.MM_sr[j++]=x; if(!x.oSrc) x.oSrc=x.src; x.src=a[i+2];}
}
//-->
</SCRIPT>
<BODY onLoad="MM_preloadImages('../img/walls_downloads/mundo_s.jpg','../img/walls_downloads/dinamica_s.jpg','../img/walls_downloads/siete_s.jpg','../img/walls_downloads/talento_s.jpg','../img/walls_downloads/target_s.jpg')">
<TABLE WIDTH="665" BORDER="0" CELLSPACING="0" CELLPADDING="0" ALIGN="right">
  <TR> 
    <TD ALIGN="center" WIDTH="113"><A HREF="javascript:openwin('wallpapers_ow.html?tapiz=mundo','fotos','width=300,height=250,scrollbars=0')" onMouseOut="MM_swapImgRestore()" onMouseOver="MM_swapImage('mundo','','../img/walls_downloads/mundo_s.jpg',1)"><IMG NAME="mundo" BORDER="0" SRC="../img/walls_downloads/mundo_s_sc.jpg" WIDTH="123" HEIGHT="92"></A></TD>
    <TD ALIGN="center" WIDTH="113"><A HREF="javascript:openwin('wallpapers_ow.html?tapiz=dinamica','fotos','width=300,height=250,scrollbars=0')" onMouseOut="MM_swapImgRestore()" onMouseOver="MM_swapImage('dinamica','','../img/walls_downloads/dinamica_s.jpg',1)"><IMG NAME="dinamica" BORDER="0" SRC="../img/walls_downloads/dinamica_s_sc.jpg" WIDTH="123" HEIGHT="92"></A></TD>
    <TD ALIGN="center" WIDTH="113"><A HREF="javascript:openwin('wallpapers_ow.html?tapiz=siete','fotos','width=300,height=250,scrollbars=0')" onMouseOut="MM_swapImgRestore()" onMouseOver="MM_swapImage('siete','','../img/walls_downloads/siete_s.jpg',1)"><IMG NAME="siete" BORDER="0" SRC="../img/walls_downloads/siete_s_sc.jpg" WIDTH="123" HEIGHT="92"></A></TD>
    <TD ALIGN="center" WIDTH="113"><A HREF="javascript:openwin('wallpapers_ow.html?tapiz=talento','fotos','width=300,height=250,scrollbars=0')" onMouseOut="MM_swapImgRestore()" onMouseOver="MM_swapImage('talento','','../img/walls_downloads/talento_s.jpg',1)"><IMG NAME="talento" BORDER="0" SRC="../img/walls_downloads/talento_s_sc.jpg" WIDTH="123" HEIGHT="92"></A></TD>
    <TD ALIGN="center" WIDTH="113"><A HREF="javascript:openwin('wallpapers_ow.html?tapiz=target','fotos','width=300,height=250,scrollbars=0')" onMouseOut="MM_swapImgRestore()" onMouseOver="MM_swapImage('target','','../img/walls_downloads/target_s.jpg',1)"><IMG NAME="target" BORDER="0" SRC="../img/walls_downloads/target_s_sc.jpg" WIDTH="123" HEIGHT="92"></A></TD>
  </TR>
</TABLE>
</HTML>