 
<TABLE WIDTH="480" BORDER="0" CELLSPACING="0" CELLPADDING="0">
  <TR BGCOLOR="#FFFFFF"> 
    <TD><IMG SRC="../img/general/spacer.gif" WIDTH="1" HEIGHT="1"><IMG SRC="../img/general/spacer.gif" WIDTH="1" HEIGHT="1"></TD>
  </TR>
</TABLE>
<TABLE WIDTH="480" BORDER="0" CELLSPACING="0" CELLPADDING="0" HEIGHT="18">
  <TR> 
    <TD BGCOLOR="#FFFFFF" WIDTH="1"><IMG SRC="../img/general/spacer.gif" WIDTH="1" HEIGHT="1"></TD>
    <TD WIDTH="478" ALIGN="right"><FONT FACE="Verdana, Arial, Helvetica, sans-serif"><B><FONT FACE="Verdana, Arial, Helvetica, sans-serif"><B><FONT FACE="Verdana, Arial, Helvetica, sans-serif"><B><FONT COLOR="#FFFFFF">Trayectoria 
      en Selecciones Juveniles</FONT></B></FONT> &nbsp;</B></FONT><FONT COLOR="#FFFFFF"> 
      </FONT>&nbsp;&nbsp;</B></FONT></TD>
    <TD BGCOLOR="#FFFFFF" WIDTH="1"><IMG SRC="../img/general/spacer.gif" WIDTH="1" HEIGHT="1"></TD>
  </TR>
</TABLE>
<TABLE WIDTH="480" BORDER="0" CELLSPACING="0" CELLPADDING="0">
  <TR BGCOLOR="#FFFFFF"> 
    <TD><IMG SRC="../img/general/spacer.gif" WIDTH="1" HEIGHT="1"><IMG SRC="../img/general/spacer.gif" WIDTH="1" HEIGHT="1"></TD>
  </TR>
</TABLE>
<TABLE WIDTH="480" BORDER="0" CELLSPACING="0" CELLPADDING="0">
  <TR> 
    <TD BGCOLOR="#FFFFFF" WIDTH="1"><IMG SRC="../img/general/spacer.gif" WIDTH="1" HEIGHT="1"></TD>
    <TD WIDTH="478" BGCOLOR="#000000" ALIGN="right"><A HREF="?inc=river"><FONT COLOR="#FFFFFF">River 
      Plate </FONT></A> <FONT COLOR="#FFFFFF">I </FONT><A HREF="?inc=seleccion"><FONT COLOR="#FFFFFF">Seleccion 
      Mayor</FONT></A>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</TD>
    <TD BGCOLOR="#FFFFFF" WIDTH="1"><IMG SRC="../img/general/spacer.gif" WIDTH="1" HEIGHT="1"></TD>
  </TR>
</TABLE>
<TABLE WIDTH="480" BORDER="0" CELLSPACING="0" CELLPADDING="0">
  <TR BGCOLOR="#FFFFFF"> 
    <TD><IMG SRC="../img/general/spacer.gif" WIDTH="1" HEIGHT="1"><IMG SRC="../img/general/spacer.gif" WIDTH="1" HEIGHT="1"></TD>
  </TR>
</TABLE>
<TABLE WIDTH="480" BORDER="0" CELLSPACING="0" CELLPADDING="0" HEIGHT="20">
  <TR> 
    <TD WIDTH="121" VALIGN="top"> 
      <TABLE WIDTH="121" BORDER="0" CELLSPACING="0" CELLPADDING="0">
        <TR> 
          <TD BGCOLOR="#FFFFFF" WIDTH="1" HEIGHT="355"><IMG SRC="../img/general/spacer.gif" WIDTH="1" HEIGHT="1"></TD>
          <TD HEIGHT="355" VALIGN="top"> 
            <TABLE WIDTH="120" BORDER="0" CELLSPACING="0" CELLPADDING="0">
              <TR BGCOLOR="#666666"> 
                <TD>&nbsp;</TD>
              </TR>
              <TR BGCOLOR="#FFFFFF"> 
                <TD><IMG SRC="../img/general/spacer.gif" WIDTH="1" HEIGHT="1" HSPACE="1"></TD>
              </TR>
              <TR BGCOLOR="#000000"> 
                <TD HEIGHT="80"><IMG SRC="../img/trayectoria/juveniles1.jpg" WIDTH="120" HEIGHT="80"></TD>
              </TR>
              <TR BGCOLOR="#666666"> 
                <TD HEIGHT="1" WIDTH="1"><IMG SRC="../img/general/spacer.gif" WIDTH="1" HEIGHT="1"></TD>
              </TR>
              <TR BGCOLOR="#000000"> 
                <TD HEIGHT="80"><IMG SRC="../img/trayectoria/juveniles2.jpg" WIDTH="120" HEIGHT="80"></TD>
              </TR>
              <TR BGCOLOR="#666666"> 
                <TD><IMG SRC="../img/general/spacer.gif" WIDTH="1" HEIGHT="1"></TD>
              </TR>
              <TR BGCOLOR="#000000"> 
                <TD HEIGHT="80"><IMG SRC="../img/trayectoria/juveniles3.jpg" WIDTH="120" HEIGHT="80"></TD>
              </TR>
              <TR BGCOLOR="#FFFFFF"> 
                <TD><IMG SRC="../img/general/spacer.gif" WIDTH="1" HEIGHT="1" HSPACE="1"></TD>
              </TR>
            </TABLE>
            <? include "menu.inc" ?> </TD>
        </TR>
      </TABLE>
    </TD>
    <TD BGCOLOR="#FFFFFF" WIDTH="1"><IMG SRC="../img/general/spacer.gif" WIDTH="1" HEIGHT="1"></TD>
    <TD WIDTH="357" VALIGN="top"> 
      <TABLE WIDTH="100%" BORDER="0" CELLSPACING="2" CELLPADDING="2">
        <TR> 
          <TD> 
            <P><B><IMG SRC="../img/general/title_1.gif" WIDTH="5" HEIGHT="5"> 
              Selecci&oacute;n juvenil sub-20</B><BR>
              No tuvo la chance de integrar en la Selecci&oacute;n Sub 20, ya 
              que los dirigentes de River no lo cedieron para disputar el Mundial 
              de Nigeria. A pesar de tener muchas ganas de representar a la Argentina, 
              Saviola respet&oacute; la decisi&oacute;n de la Comisi&oacute;n 
              Directiva: &quot;Cualquier jugador se siente mal por no poder jugar 
              un mundial, pero es la decisi&oacute;n de los dirigentes y tengo 
              que aceptarla, porque este es el club que me dio todo&quot;. La 
              Argentina sinti&oacute; la ausencia de Javeir, al igual que la de 
              Aimar, y disput&oacute; un torneo muy pobre, quedando eliminado 
              en octavos de final, a manos de M&eacute;xico. </P>
            <P><B><IMG SRC="../img/general/title_1.gif" WIDTH="5" HEIGHT="5"> 
              Selecci&oacute;n juvenil sub-23</B><BR>
              Dos d&iacute;as despu&eacute;s de haberse cumplido un a&ntilde;o 
              de su debut en Primera Divisi&oacute;n, Saviola jug&oacute; su primer 
              partido con la casaca albiceleste. Fue para la selecci&oacute;n 
              Sub-23, el 20 de octubre de 1999, en un amistoso en que derrot&oacute; 
              a Bolivia 1 a 0, en el estadio de Gimnasia y Tiro de Salta.<BR>
              Su primer gol con la Sub-23 lo marc&oacute; en el segundo partido, 
              ante Polonia, en otro amistoso disputado en el estadio de Gimnasia 
              y Esgrima La Plata, en que Argentina se impuso por 5 a 0.<BR>
              En febrero de 2000 particip&oacute; del fracaso argentino en el 
              preol&iacute;mpico de Brasil, donde la selecci&oacute;n qued&oacute; 
              afuera de los Juegos de Sydney. En aquella ocasi&oacute;n Saviola 
              disput&oacute; 7 partidos; 3 de ellos como titular, y no pudo convertir 
              ning&uacute;n tanto.</P>
            <TABLE WIDTH="340" BORDER="0" CELLSPACING="0" CELLPADDING="0" ALIGN="center">
              <TR> 
                <TD> 
                  <P></P>
                  <TABLE WIDTH="340" BORDER="0" CELLSPACING="0" CELLPADDING="0">
                    <TR BGCOLOR="#FFFFFF"> 
                      <TD><IMG SRC="../img/general/spacer.gif" WIDTH="1" HEIGHT="1"></TD>
                    </TR>
                  </TABLE>
                  <TABLE WIDTH="340" BORDER="0" CELLSPACING="0" CELLPADDING="0">
                    <TR> 
                      <TD BGCOLOR="#FFFFFF" WIDTH="1"><IMG SRC="../img/general/spacer.gif" WIDTH="1" HEIGHT="1"></TD>
                      <TD WIDTH="348"> 
                        <TABLE WIDTH="100%" BORDER="0" CELLSPACING="1" CELLPADDING="1">
                          <TR> 
                            <TD WIDTH="200" ALIGN="center" BGCOLOR="#000000">Motivo</TD>
                            <TD ALIGN="center" WIDTH="70" BGCOLOR="#000000">Partidos</TD>
                            <TD WIDTH="70" ALIGN="center" BGCOLOR="#000000">Goles</TD>
                          </TR>
                          <? 
	$totalp = 0;
	$totalg = 0;
	$zona = mysql_query("SELECT * from partidos_campeonato WHERE zona='menores'");
	while($row=mysql_fetch_object($zona)){ 
		$part = mysql_query("SELECT * from partidos WHERE campeonato='$row->campeonato'");
		$partidos = mysql_num_rows($part);
		$g = mysql_query("SELECT * from partidos WHERE campeonato='$row->campeonato'");
			$cantidad=0;
			while($gol=mysql_fetch_object($g)){
			$cantidad=$cantidad+$gol->goles;
			}
?> 
                          <TR> 
                            <TD WIDTH="200" ALIGN="center" BGCOLOR="#666666"><A HREF="javascript:openwin('partidos_ow.html?id=<? echo $row->id ?>','Estadística','width=506,height=250,scrollbars=1')"> 
                              <FONT FACE="Ms Sans Serif" SIZE="1" COLOR="#FFFFFF"><? echo $row->campeonato ?> 
                              &nbsp; &gt;&gt; </FONT></A></TD>
                            <TD ALIGN="center" WIDTH="70" BGCOLOR="#666666"><? echo $partidos ?></TD>
                            <TD WIDTH="70" ALIGN="center" BGCOLOR="#666666"><? echo $cantidad ?></TD>
                          </TR>
                          <? 
		$totalp = $totalp+$partidos;
		$totalg = $totalg+$cantidad;
} 
?> 
                          <TR BGCOLOR="#555555"> 
                            <TD WIDTH="200" ALIGN="center"><B>TOTAL</B></TD>
                            <TD ALIGN="center" WIDTH="70"><B><? echo $totalp ?></B></TD>
                            <TD WIDTH="70" ALIGN="center"><B><? echo $totalg ?></B></TD>
                          </TR>
                        </TABLE>
                      </TD>
                      <TD BGCOLOR="#FFFFFF" WIDTH="1"><IMG SRC="../img/general/spacer.gif" WIDTH="1" HEIGHT="1"></TD>
                    </TR>
                  </TABLE>
                  <TABLE WIDTH="340" BORDER="0" CELLSPACING="0" CELLPADDING="0">
                    <TR BGCOLOR="#FFFFFF"> 
                      <TD><IMG SRC="../img/general/spacer.gif" WIDTH="1" HEIGHT="1"></TD>
                    </TR>
                  </TABLE>
                </TD>
              </TR>
            </TABLE>
          </TD>
        </TR>
      </TABLE>
      <IMG SRC="../img/general/spacer.gif" WIDTH="1" HEIGHT="1"></TD>
<TD BGCOLOR="#FFFFFF" WIDTH="1" BACKGROUND="../img/general/title_1.gif"><IMG SRC="../img/general/spacer.gif" WIDTH="1" HEIGHT="1"></TD>
              
  </TR>
</TABLE>
<TABLE WIDTH="480" BORDER="0" CELLSPACING="0" CELLPADDING="0" HEIGHT="1">
  <TR> 
    <TD WIDTH="120"><IMG SRC="../img/general/spacer.gif" WIDTH="1" HEIGHT="1"></TD>
    <TD BGCOLOR="#FFFFFF" WIDTH="358"><IMG SRC="../img/general/spacer.gif" WIDTH="1" HEIGHT="1"></TD>
  </TR>
</TABLE>
