 
<TABLE WIDTH="480" BORDER="0" CELLSPACING="0" CELLPADDING="0">
  <TR BGCOLOR="#FFFFFF"> 
    <TD><IMG SRC="../img/general/spacer.gif" WIDTH="1" HEIGHT="1"><IMG SRC="../img/general/spacer.gif" WIDTH="1" HEIGHT="1"></TD>
  </TR>
</TABLE>
<TABLE WIDTH="480" BORDER="0" CELLSPACING="0" CELLPADDING="0" HEIGHT="18">
  <TR> 
    <TD BGCOLOR="#FFFFFF" WIDTH="1"><IMG SRC="../img/general/spacer.gif" WIDTH="1" HEIGHT="1"></TD>
    <TD WIDTH="478" ALIGN="right"><FONT FACE="Verdana, Arial, Helvetica, sans-serif"><B><FONT COLOR="#FFFFFF">Logros 
      Personales y Profesionales</FONT>&nbsp;&nbsp;</B></FONT></TD>
    <TD BGCOLOR="#FFFFFF" WIDTH="1"><IMG SRC="../img/general/spacer.gif" WIDTH="1" HEIGHT="1"></TD>
  </TR>
</TABLE>
<TABLE WIDTH="480" BORDER="0" CELLSPACING="0" CELLPADDING="0">
  <TR BGCOLOR="#FFFFFF"> 
    <TD><IMG SRC="../img/general/spacer.gif" WIDTH="1" HEIGHT="1"><IMG SRC="../img/general/spacer.gif" WIDTH="1" HEIGHT="1"></TD>
  </TR>
</TABLE>
<TABLE WIDTH="480" BORDER="0" CELLSPACING="0" CELLPADDING="0">
  <TR> 
    <TD BGCOLOR="#FFFFFF" WIDTH="1"><IMG SRC="../img/general/spacer.gif" WIDTH="1" HEIGHT="1"></TD>
    <TD WIDTH="478" BGCOLOR="#000000" ALIGN="right">&nbsp;</TD>
    <TD BGCOLOR="#FFFFFF" WIDTH="1"><IMG SRC="../img/general/spacer.gif" WIDTH="1" HEIGHT="1"></TD>
  </TR>
</TABLE>
<TABLE WIDTH="480" BORDER="0" CELLSPACING="0" CELLPADDING="0">
  <TR BGCOLOR="#FFFFFF"> 
    <TD><IMG SRC="../img/general/spacer.gif" WIDTH="1" HEIGHT="1"><IMG SRC="../img/general/spacer.gif" WIDTH="1" HEIGHT="1"></TD>
  </TR>
</TABLE>
<TABLE WIDTH="480" BORDER="0" CELLSPACING="0" CELLPADDING="0" HEIGHT="20">
  <TR> 
    <TD WIDTH="121" VALIGN="top"> 
      <TABLE WIDTH="121" BORDER="0" CELLSPACING="0" CELLPADDING="0">
        <TR> 
          <TD BGCOLOR="#FFFFFF" WIDTH="1" HEIGHT="355"><IMG SRC="../img/general/spacer.gif" WIDTH="1" HEIGHT="1"></TD>
          <TD HEIGHT="355" VALIGN="top"> 
            <TABLE WIDTH="120" BORDER="0" CELLSPACING="0" CELLPADDING="0">
              <TR BGCOLOR="#666666"> 
                <TD>&nbsp;</TD>
              </TR>
              <TR BGCOLOR="#FFFFFF"> 
                <TD><IMG SRC="../img/general/spacer.gif" WIDTH="1" HEIGHT="1" HSPACE="1"></TD>
              </TR>
              <TR BGCOLOR="#000000"> 
                <TD HEIGHT="80"><IMG SRC="../img/trayectoria/logros1.jpg" WIDTH="120" HEIGHT="80"></TD>
              </TR>
              <TR BGCOLOR="#666666"> 
                <TD HEIGHT="1" WIDTH="1"><IMG SRC="../img/general/spacer.gif" WIDTH="1" HEIGHT="1"></TD>
              </TR>
              <TR BGCOLOR="#000000"> 
                <TD HEIGHT="80"><IMG SRC="../img/trayectoria/logros2.jpg" WIDTH="120" HEIGHT="80"></TD>
              </TR>
              <TR BGCOLOR="#666666"> 
                <TD><IMG SRC="../img/general/spacer.gif" WIDTH="1" HEIGHT="1"></TD>
              </TR>
              <TR BGCOLOR="#000000"> 
                <TD HEIGHT="80"><IMG SRC="../img/trayectoria/logros3.jpg" WIDTH="120" HEIGHT="80"></TD>
              </TR>
              <TR BGCOLOR="#FFFFFF"> 
                <TD><IMG SRC="../img/general/spacer.gif" WIDTH="1" HEIGHT="1" HSPACE="1"></TD>
              </TR>
            </TABLE>
            <? include "menu.inc" ?> </TD>
        </TR>
      </TABLE>
    </TD>
    <TD BGCOLOR="#FFFFFF" WIDTH="1"><IMG SRC="../img/general/spacer.gif" WIDTH="1" HEIGHT="1"></TD>
    <TD WIDTH="357" VALIGN="top"> 
      <TABLE WIDTH="100%" BORDER="0" CELLSPACING="2" CELLPADDING="2">
        <TR> 
          <TD> <BR>
            <TABLE WIDTH="95%" BORDER="0" ALIGN="center">
              <TR> 
                <TD WIDTH="10"><IMG SRC="../img/general/title_1.gif" WIDTH="5" HEIGHT="5"></TD>
                <TD VALIGN="top"> <B>Campeonato Apertura 1999 de Primera División</B></TD>
              </TR>
              <TR> 
                <TD WIDTH="10">&nbsp;</TD>
                <TD VALIGN="top">Fue el primer título profesional obtenido de 
                  la mano de Ramón Díaz, técnico que lo hizo debutar a los 16 
                  a&ntilde;os. Torneo en el cual se afianz&oacute; una temible 
                  delantera, compuesta por el, Pablo Aimar y Juan Pablo Ángel.<BR>
                </TD>
              </TR>
              <TR> 
                <TD WIDTH="10"><IMG SRC="../img/general/spacer.gif" WIDTH="1" HEIGHT="1"></TD>
                <TD VALIGN="top"><IMG SRC="../img/general/title_1.gif" WIDTH="100%" HEIGHT="1"></TD>
              </TR>
              <TR> 
                <TD WIDTH="10"><IMG SRC="../img/general/title_1.gif" WIDTH="5" HEIGHT="5"></TD>
                <TD VALIGN="top"><B>Goleador del Campeonato Apertura 1999</B></TD>
              </TR>
              <TR> 
                <TD WIDTH="10">&nbsp;</TD>
                <TD VALIGN="top">Con 15 goles para todos los gustos: de derecha, 
                  de cabeza, de chilena y de penal. Algunos fueron espectaculares 
                  y otros decisivos. Pero todos sirvieron para llevar a River 
                  hacia la conquista de su 28° título.<BR>
                </TD>
              </TR>
              <TR> 
                <TD WIDTH="10"><IMG SRC="../img/general/spacer.gif" WIDTH="1" HEIGHT="1"></TD>
                <TD VALIGN="top"><IMG SRC="../img/general/title_1.gif" WIDTH="100%" HEIGHT="1"></TD>
              </TR>
              <TR> 
                <TD WIDTH="10"><IMG SRC="../img/general/title_1.gif" WIDTH="5" HEIGHT="5"></TD>
                <TD VALIGN="top"><B>Mejor jugador de América de 1999</B></TD>
              </TR>
              <TR> 
                <TD WIDTH="10">&nbsp;</TD>
                <TD VALIGN="top">Primera distinción internacional para Saviola, 
                  luego de un magnífico Torneo Apertura, que lo tuvo como goleador 
                  y campeón.<BR>
                </TD>
              </TR>
              <TR> 
                <TD width="10"><IMG src="../img/general/spacer.gif" width="1" height="1"></TD>
                <TD valign="top"><IMG src="../img/general/title_1.gif" width="100%" height="1"></TD>
              </TR>
              <TR> 
                <TD width="10"><IMG src="../img/general/title_1.gif" width="5" height="5"></TD>
                <TD valign="top"><B>Olimpia de Plata en F&uacute;tbol en 1999</B></TD>
              </TR>
              <TR> 
                <TD width="10">&nbsp;</TD>
                <TD valign="top">El máximo premio deportivo a nivel nacional lo 
                  obtuvo el 20 de diciembre de 1999, tras superar en la terna 
                  nada menos que a Juan Román Riquelme y a Pablo Aimar.<BR>
                </TD>
              </TR>
              <TR> 
                <TD width="10"><IMG src="../img/general/spacer.gif" width="1" height="1"></TD>
                <TD valign="top"><IMG src="../img/general/title_1.gif" width="100%" height="1"></TD>
              </TR>
              <TR> 
                <TD width="10"><IMG src="../img/general/title_1.gif" width="5" height="5"></TD>
                <TD valign="top"><B>Campeonato Clausura 2000 de Primera División</B></TD>
              </TR>
              <TR> 
                <TD width="10">&nbsp;</TD>
                <TD valign="top">Con la misma fórmula que en 1999, formando el 
                  trío con Aimar y Ángel, pero esta vez con Américo Rub&eacute;n 
                  Gallego como DT.<BR>
                </TD>
              </TR>
              <TR> 
                <TD width="10"><IMG src="../img/general/spacer.gif" width="1" height="1"></TD>
                <TD valign="top"><IMG src="../img/general/title_1.gif" width="100%" height="1"></TD>
              </TR>
              <TR> 
                <TD width="10">&nbsp;</TD>
                <TD valign="top">&nbsp;</TD>
              </TR>
            </TABLE>
            <P>&nbsp;</P>
            </TD>
        </TR>
      </TABLE>
      <IMG SRC="../img/general/spacer.gif" WIDTH="1" HEIGHT="1"></TD>
<TD BGCOLOR="#FFFFFF" WIDTH="1" BACKGROUND="../img/general/title_1.gif"><IMG SRC="../img/general/spacer.gif" WIDTH="1" HEIGHT="1"></TD>
              
  </TR>
</TABLE>
<TABLE WIDTH="480" BORDER="0" CELLSPACING="0" CELLPADDING="0" HEIGHT="1">
  <TR> 
    <TD WIDTH="120"><IMG SRC="../img/general/spacer.gif" WIDTH="1" HEIGHT="1"></TD>
    <TD BGCOLOR="#FFFFFF" WIDTH="358"><IMG SRC="../img/general/spacer.gif" WIDTH="1" HEIGHT="1"></TD>
  </TR>
</TABLE>
