<TABLE WIDTH="120" BORDER="0" CELLSPACING="0" CELLPADDING="0">
  <TR> 
    <TD HEIGHT="30">&nbsp;</TD>
  </TR>
  <TR BGCOLOR="#FFFFFF"> 
    <TD><IMG SRC="../img/general/spacer.gif" WIDTH="1" HEIGHT="1"></TD>
  </TR>
  <TR> 
    <TD> 
      <TABLE WIDTH="120" BORDER="0" CELLSPACING="0" CELLPADDING="0">
        <TR> 
          <TD WIDTH="24" BGCOLOR="#6D99A7" ALIGN="center"><IMG SRC="../img/general/noticias/news_icon.gif" WIDTH="21" HEIGHT="25"></TD>
          <TD BGCOLOR="#FFFFFF" WIDTH="1"><IMG SRC="../img/general/spacer.gif" WIDTH="1" HEIGHT="1"></TD>
          <TD WIDTH="95" BGCOLOR="#6D99A7">&nbsp;&gt;<A HREF="?inc=vida"><FONT COLOR="#FFFFFF"> Vida</FONT></A></TD>
        </TR>
      </TABLE>
      <TABLE WIDTH="120" BORDER="0" CELLSPACING="0" CELLPADDING="0">
        <TR BGCOLOR="#FFFFFF"> 
          <TD HEIGHT="1"><IMG SRC="../img/general/spacer.gif" WIDTH="1" HEIGHT="1"></TD>
        </TR>
      </TABLE>
      <TABLE WIDTH="120" BORDER="0" CELLSPACING="0" CELLPADDING="0">
        <TR> 
          <TD WIDTH="24" BGCOLOR="#6D99A7"><IMG SRC="../img/general/noticias/news_icon.gif" WIDTH="21" HEIGHT="25"></TD>
          <TD BGCOLOR="#FFFFFF" WIDTH="1"><IMG SRC="../img/general/spacer.gif" WIDTH="1" HEIGHT="1"></TD>
          <TD WIDTH="95" BGCOLOR="#6D99A7">&nbsp;&gt; <A HREF="?inc=logros"><FONT COLOR="#FFFFFF">Logros</FONT></A> 
          </TD>
        </TR>
      </TABLE>
      <TABLE WIDTH="120" BORDER="0" CELLSPACING="0" CELLPADDING="0">
        <TR BGCOLOR="#FFFFFF"> 
          <TD HEIGHT="1"><IMG SRC="../img/general/spacer.gif" WIDTH="1" HEIGHT="1"></TD>
        </TR>
      </TABLE>
      <TABLE WIDTH="120" BORDER="0" CELLSPACING="0" CELLPADDING="0">
        <TR> 
          <TD WIDTH="24" BGCOLOR="#6D99A7"><IMG SRC="../img/general/noticias/news_icon.gif" WIDTH="21" HEIGHT="25"></TD>
          <TD BGCOLOR="#FFFFFF" WIDTH="1"><IMG SRC="../img/general/spacer.gif" WIDTH="1" HEIGHT="1"></TD>
          <TD WIDTH="95" BGCOLOR="#6D99A7">&nbsp;&gt; <A HREF="?inc=goles"><FONT COLOR="#FFFFFF">Los 
            Goles</FONT></A></TD>
        </TR>
      </TABLE>
      <TABLE WIDTH="120" BORDER="0" CELLSPACING="0" CELLPADDING="0">
        <TR BGCOLOR="#FFFFFF"> 
          <TD HEIGHT="1"><IMG SRC="../img/general/spacer.gif" WIDTH="1" HEIGHT="1"></TD>
        </TR>
      </TABLE>
      <TABLE WIDTH="120" BORDER="0" CELLSPACING="0" CELLPADDING="0">
        <TR> 
          <TD WIDTH="24" BGCOLOR="#6D99A7"><IMG SRC="../img/general/noticias/news_icon.gif" WIDTH="21" HEIGHT="25"></TD>
          <TD BGCOLOR="#FFFFFF" WIDTH="1"><IMG SRC="../img/general/spacer.gif" WIDTH="1" HEIGHT="1"></TD>
          <TD WIDTH="95" BGCOLOR="#6D99A7">&nbsp;&gt; <A HREF="?inc=completas"><FONT COLOR="#FFFFFF">Estad&iacute;sticas</FONT></A></TD>
        </TR>
      </TABLE>
      <TABLE WIDTH="120" BORDER="0" CELLSPACING="0" CELLPADDING="0">
        <TR BGCOLOR="#FFFFFF"> 
          <TD HEIGHT="1"><IMG SRC="../img/general/spacer.gif" WIDTH="1" HEIGHT="1"></TD>
        </TR>
      </TABLE>
      <TABLE WIDTH="120" BORDER="0" CELLSPACING="0" CELLPADDING="0">
        <TR> 
          <TD WIDTH="24" BGCOLOR="#6D99A7"><IMG SRC="../img/general/noticias/news_icon.gif" WIDTH="21" HEIGHT="25"></TD>
          <TD BGCOLOR="#FFFFFF" WIDTH="1"><IMG SRC="../img/general/spacer.gif" WIDTH="1" HEIGHT="1"></TD>
          <TD WIDTH="95" BGCOLOR="#6D99A7">&nbsp;&gt;<A HREF="?inc=river"><FONT COLOR="#FFFFFF">Trayectoria</FONT></A></TD>
        </TR>
 </TABLE>
      <TABLE WIDTH="120" BORDER="0" CELLSPACING="0" CELLPADDING="0">
        <TR BGCOLOR="#FFFFFF"> 
          <TD HEIGHT="1"><IMG SRC="../img/general/spacer.gif" WIDTH="1" HEIGHT="1"></TD>
        </TR>
      </TABLE>
      <TABLE WIDTH="120" BORDER="0" CELLSPACING="0" CELLPADDING="0">
        <TR> 
          <TD WIDTH="24" BGCOLOR="#6D99A7"><IMG SRC="../img/general/noticias/news_icon.gif" WIDTH="21" HEIGHT="25"></TD>
          <TD BGCOLOR="#FFFFFF" WIDTH="1"><IMG SRC="../img/general/spacer.gif" WIDTH="1" HEIGHT="1"></TD>
          <TD WIDTH="95" BGCOLOR="#6D99A7">&nbsp;&gt;<A HREF="?inc=se_dice"><FONT COLOR="#FFFFFF">Se 
            dice de M&iacute;</FONT></A></TD>
        </TR>
 </TABLE>
      <TABLE WIDTH="120" BORDER="0" CELLSPACING="0" CELLPADDING="0">
        <TR BGCOLOR="#FFFFFF"> 
          <TD HEIGHT="1"><IMG SRC="../img/general/spacer.gif" WIDTH="1" HEIGHT="1"></TD>
        </TR>
      </TABLE>
      <TABLE WIDTH="120" BORDER="0" CELLSPACING="0" CELLPADDING="0">
        <TR> 
          <TD WIDTH="24" BGCOLOR="#6D99A7"><IMG SRC="../img/general/noticias/news_icon.gif" WIDTH="21" HEIGHT="25"></TD>
          <TD BGCOLOR="#FFFFFF" WIDTH="1"><IMG SRC="../img/general/spacer.gif" WIDTH="1" HEIGHT="1"></TD>
          <TD WIDTH="95" BGCOLOR="#6D99A7">&nbsp;&gt;<A HREF="?inc=mis_idolos"><FONT COLOR="#FFFFFF">Mis 
            &Iacute;dolos </FONT></A></TD>
        </TR>
      </TABLE>
    </TD>
  </TR>
  <TR BGCOLOR="#FFFFFF"> 
    <TD><IMG SRC="../img/general/spacer.gif" WIDTH="1" HEIGHT="1"></TD>
  </TR>
</TABLE>