 
<TABLE WIDTH="480" BORDER="0" CELLSPACING="0" CELLPADDING="0">
  <TR BGCOLOR="#FFFFFF"> 
    <TD><IMG SRC="../img/general/spacer.gif" WIDTH="1" HEIGHT="1"><IMG SRC="../img/general/spacer.gif" WIDTH="1" HEIGHT="1"></TD>
  </TR>
</TABLE>
<TABLE WIDTH="480" BORDER="0" CELLSPACING="0" CELLPADDING="0" HEIGHT="18">
  <TR> 
    <TD BGCOLOR="#FFFFFF" WIDTH="1"><IMG SRC="../img/general/spacer.gif" WIDTH="1" HEIGHT="1"></TD>
    <TD WIDTH="478" ALIGN="right"><FONT FACE="Verdana, Arial, Helvetica, sans-serif"><B><FONT FACE="Verdana, Arial, Helvetica, sans-serif"><B><FONT FACE="Verdana, Arial, Helvetica, sans-serif"><B><FONT COLOR="#FFFFFF">Trayectoria 
      en River Plate</FONT></B></FONT> &nbsp;</B></FONT><FONT COLOR="#FFFFFF"> 
      </FONT>&nbsp;&nbsp;</B></FONT></TD>
    <TD BGCOLOR="#FFFFFF" WIDTH="1"><IMG SRC="../img/general/spacer.gif" WIDTH="1" HEIGHT="1"></TD>
  </TR>
</TABLE>
<TABLE WIDTH="480" BORDER="0" CELLSPACING="0" CELLPADDING="0">
  <TR BGCOLOR="#FFFFFF"> 
    <TD><IMG SRC="../img/general/spacer.gif" WIDTH="1" HEIGHT="1"><IMG SRC="../img/general/spacer.gif" WIDTH="1" HEIGHT="1"></TD>
  </TR>
</TABLE>
<TABLE WIDTH="480" BORDER="0" CELLSPACING="0" CELLPADDING="0">
  <TR> 
    <TD BGCOLOR="#FFFFFF" WIDTH="1"><IMG SRC="../img/general/spacer.gif" WIDTH="1" HEIGHT="1"></TD>
    <TD WIDTH="478" BGCOLOR="#000000" ALIGN="right"><A HREF="?inc=seleccion"><FONT COLOR="#FFFFFF">Selecci&oacute;n 
      Mayor</FONT></A> <FONT COLOR="#FFFFFF">I </FONT><A HREF="?inc=juveniles"><FONT COLOR="#FFFFFF">Selecciones 
      Juveniles</FONT></A>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</TD>
    <TD BGCOLOR="#FFFFFF" WIDTH="1"><IMG SRC="../img/general/spacer.gif" WIDTH="1" HEIGHT="1"></TD>
  </TR>
</TABLE>
<TABLE WIDTH="480" BORDER="0" CELLSPACING="0" CELLPADDING="0">
  <TR BGCOLOR="#FFFFFF"> 
    <TD><IMG SRC="../img/general/spacer.gif" WIDTH="1" HEIGHT="1"><IMG SRC="../img/general/spacer.gif" WIDTH="1" HEIGHT="1"></TD>
  </TR>
</TABLE>
<TABLE WIDTH="480" BORDER="0" CELLSPACING="0" CELLPADDING="0" HEIGHT="20">
  <TR> 
    <TD WIDTH="121" VALIGN="top"> 
      <TABLE WIDTH="121" BORDER="0" CELLSPACING="0" CELLPADDING="0">
        <TR> 
          <TD BGCOLOR="#FFFFFF" WIDTH="1" HEIGHT="355"><IMG SRC="../img/general/spacer.gif" WIDTH="1" HEIGHT="1"></TD>
          <TD HEIGHT="355" VALIGN="top"> 
            <TABLE WIDTH="120" BORDER="0" CELLSPACING="0" CELLPADDING="0">
              <TR BGCOLOR="#666666"> 
                <TD>&nbsp;</TD>
              </TR>
              <TR BGCOLOR="#FFFFFF"> 
                <TD><IMG SRC="../img/general/spacer.gif" WIDTH="1" HEIGHT="1" HSPACE="1"></TD>
              </TR>
              <TR BGCOLOR="#000000"> 
                <TD HEIGHT="80"><IMG SRC="../img/trayectoria/river1.jpg" WIDTH="120" HEIGHT="80"></TD>
              </TR>
              <TR BGCOLOR="#666666"> 
                <TD HEIGHT="1" WIDTH="1"><IMG SRC="../img/general/spacer.gif" WIDTH="1" HEIGHT="1"></TD>
              </TR>
              <TR BGCOLOR="#000000"> 
                <TD HEIGHT="80"><IMG SRC="../img/trayectoria/river2.jpg" WIDTH="120" HEIGHT="80"></TD>
              </TR>
              <TR BGCOLOR="#666666"> 
                <TD><IMG SRC="../img/general/spacer.gif" WIDTH="1" HEIGHT="1"></TD>
              </TR>
              <TR BGCOLOR="#000000"> 
                <TD HEIGHT="80"><IMG SRC="../img/trayectoria/river3.jpg" WIDTH="120" HEIGHT="80"></TD>
              </TR>
              <TR BGCOLOR="#FFFFFF"> 
                <TD><IMG SRC="../img/general/spacer.gif" WIDTH="1" HEIGHT="1" HSPACE="1"></TD>
              </TR>
            </TABLE>
            <? include "menu.inc" ?> </TD>
        </TR>
      </TABLE>
    </TD>
    <TD BGCOLOR="#FFFFFF" WIDTH="1"><IMG SRC="../img/general/spacer.gif" WIDTH="1" HEIGHT="1"></TD>
    <TD WIDTH="357" VALIGN="top"> 
            
      <TABLE CELLPADDING="2" CELLSPACING="2">
        <TR> 
                
          <TD> 
            <P>Peque&ntilde;o, con cara de p&iacute;caro y un enorme camino por 
              andar, lleg&oacute; Javier al Club Atl&eacute;tico River Plate con 
              un bolsito cargado de ilusiones y un sue&ntilde;o, que al mirarlo 
              en este presente repleto de triunfos, parece un sue&ntilde;o poco 
              ambicioso para tanto talento: llegar a Primera parec&iacute;a ser, 
              en ese entonces, una utop&iacute;a.<BR>
              Javier entr&oacute; al club millonario cuando apenas ten&iacute;a 
              8 a&ntilde;os y Jos&eacute; Curti, fue el seleccionador de jugadores 
              quien lo fich&oacute; para las inferiores de River.<BR>
              En las categor&iacute;as 8&deg; y 9&deg;, no jugaba demasiado; alternaba 
              muy seguido en el banco de suplentes, ya que lo consideraban muy 
              &quot;chiquito&quot;. <BR>
              Sin embargo, la vida le deparaba una gran sorpresa. Fue en 1998 
              cuando lleg&oacute; el cambio que lo hizo saltar de la sexta a la 
              tercera, y luego de 4 entrenamientos con el plantel de primera, 
              le lleg&oacute; el broche de oro, o mejor dicho, el comienzo de 
              una carrera llena de gloria.<BR>
              Jam&aacute;s borrar&aacute; de su memoria, el d&iacute;a que supo 
              que Ram&oacute;n D&iacute;az lo quer&iacute;a en el banco para el 
              partido contra Gimnasia de Jujuy: &quot;En River, la lista de los 
              jugadores citados para los partidos la anotan en un pizarr&oacute;n 
              del vestuario. Era mi cuarto entrenamiento con el plantel profesional 
              y antes de ba&ntilde;arme empec&eacute; a leer los apellidos, y 
              el &uacute;ltimo era el m&iacute;o. No lo pod&iacute;a creer; la 
              mir&eacute; como tres veces para ver si era verdad. En mi casa estaban 
              preocupados porque eran las 20.30 y no hab&iacute;a llegado. Mi 
              pap&aacute; -Roberto- me estaba esperando en la parada del colectivo 
              y apenas baj&eacute; le di la noticia; nos dimos un abrazo y festejamos&quot;, 
              dijo con la emoci&oacute;n de un conejo que consigue su zanahoria. 
              Y sigui&oacute;: &quot;Esa noche no pude dormir. Fue todo demasiado 
              r&aacute;pido y trataba de encontrarle alguna explicaci&oacute;n 
              a todo esto. Ten&iacute;a la posibilidad de tirar una pared con 
              los mismos jugadores que miraba por la televisi&oacute;n...&quot; 
              La explicaci&oacute;n estaba en sus pies, la explicaci&oacute;n 
              estaba en el amor al buen f&uacute;tbol, en su pasi&oacute;n por 
              la pelota.<BR>
              Y lleg&oacute; el d&iacute;a de concretar el sue&ntilde;o. Javier 
              debut&oacute; en la primera de River el 18 octubre de 1998, ante 
              Gimnasia de Jujuy, y se dio el gusto de comenzar con toda su raza 
              goleadora. Convirti&oacute; un tanto, y River empat&oacute; de visitante 
              2 a 2. Ram&oacute;n D&iacute;az, su t&eacute;cnico, confi&oacute; 
              en el pibe que ven&iacute;a de la cuarta, supo ver a un futuro &quot;crack&quot; 
              y Saviola, quien ingres&oacute; a los 15 minutos del segundo tiempo, 
              por Cristian Castillo, no lo defraud&oacute;.<BR>
              Por estos d&iacute;as, Javier Saviola est&aacute; disputando su 
              tercer temporada en el club de sus amores, y si fuera por los hinchas, 
              ser&aacute;n muchas temporadas m&aacute;s. Pero los chicos crecen, 
              y se hacen grandes, y Javier madur&oacute; lo suficiente como para 
              transformar el deseo de la gente en un imposible. Teniendo en cuenta 
              que equipos importantes de Europa, como Lazio, Juventus y especialmente 
              Barcelona, se interesaron por los servicios del conejo, y si bien 
              no concretaron su compra, tampoco descartan incorporar en sus filas 
              al 7 millonario para futuros compromisos.</P>
            <P>Los n&uacute;meros hablan por s&iacute; solos: a continuaci&oacute;n, 
              el detalle de los torneos jugados, todos los partidos y todos los 
              goles del Conejo con la camiseta de River, y con la selecci&oacute;n 
              Nacional. </P>
            <P>Torneos Locales: </P>
            <TABLE WIDTH="340" BORDER="0" CELLSPACING="0" CELLPADDING="0" ALIGN="center">
              <TR> 
                <TD> 
                  <P></P>
                  <TABLE WIDTH="340" BORDER="0" CELLSPACING="0" CELLPADDING="0">
                    <TR BGCOLOR="#FFFFFF"> 
                      <TD><IMG SRC="../img/general/spacer.gif" WIDTH="1" HEIGHT="1"></TD>
                    </TR>
                  </TABLE>
                  <TABLE WIDTH="340" BORDER="0" CELLSPACING="0" CELLPADDING="0">
                    <TR> 
                      <TD BGCOLOR="#FFFFFF" WIDTH="1"><IMG SRC="../img/general/spacer.gif" WIDTH="1" HEIGHT="1"></TD>
                      <TD WIDTH="340"> 
                        <TABLE WIDTH="100%" BORDER="0" CELLSPACING="1" CELLPADDING="1">
                          <TR> 
                            <TD WIDTH="200" ALIGN="center" BGCOLOR="#000000">Motivo</TD>
                            <TD ALIGN="center" WIDTH="70" BGCOLOR="#000000">Partidos</TD>
                            <TD WIDTH="70" ALIGN="center" BGCOLOR="#000000">Goles</TD>
                          </TR>
                          <? 
	$totalp = 0;
	$totalg = 0;
	$zona = mysql_query("SELECT * from partidos_campeonato WHERE zona='local'");
	while($row=mysql_fetch_object($zona)){ 
		$part = mysql_query("SELECT * from partidos WHERE campeonato='$row->campeonato'");
		$partidos = mysql_num_rows($part);
		$g = mysql_query("SELECT * from partidos WHERE campeonato='$row->campeonato'");
			$cantidad=0;
			while($gol=mysql_fetch_object($g)){
			$cantidad=$cantidad+$gol->goles;
			}
?> 
                          <TR> 
                            <TD WIDTH="200" ALIGN="center" BGCOLOR="#666666"><A HREF="javascript:openwin('partidos_ow.html?id=<? echo $row->id ?>','Estadística','width=506,height=250,scrollbars=1')"> 
                              <FONT FACE="Ms Sans Serif" SIZE="1" COLOR="#FFFFFF"><? echo $row->campeonato ?> 
                              &nbsp; &gt;&gt; </FONT></A></TD>
                            <TD ALIGN="center" WIDTH="70" BGCOLOR="#666666"><? echo $partidos ?></TD>
                            <TD WIDTH="70" ALIGN="center" BGCOLOR="#666666"><? echo $cantidad ?></TD>
                          </TR>
                          <? 
		$totalp = $totalp+$partidos;
		$totalg = $totalg+$cantidad;
} 
?> 
                          <TR BGCOLOR="#555555"> 
                            <TD WIDTH="200" ALIGN="center"><B>TOTAL</B></TD>
                            <TD ALIGN="center" WIDTH="70"><B><? echo $totalp ?></B></TD>
                            <TD WIDTH="70" ALIGN="center"><B><? echo $totalg ?></B></TD>
                          </TR>
                        </TABLE>
                      </TD>
                      <TD BGCOLOR="#FFFFFF" WIDTH="1"><IMG SRC="../img/general/spacer.gif" WIDTH="1" HEIGHT="1"></TD>
                    </TR>
                  </TABLE>
                  <TABLE WIDTH="340" BORDER="0" CELLSPACING="0" CELLPADDING="0">
                    <TR BGCOLOR="#FFFFFF"> 
                      <TD><IMG SRC="../img/general/spacer.gif" WIDTH="1" HEIGHT="1"></TD>
                    </TR>
                  </TABLE>
                </TD>
              </TR>
            </TABLE>
            <P>Copas Sudamericanas: <BR>
            </P>
            <TABLE WIDTH="340" BORDER="0" CELLSPACING="0" CELLPADDING="0" ALIGN="center">
              <TR> 
                <TD> 
                  <P></P>
                  <TABLE WIDTH="340" BORDER="0" CELLSPACING="0" CELLPADDING="0">
                    <TR BGCOLOR="#FFFFFF"> 
                      <TD><IMG SRC="../img/general/spacer.gif" WIDTH="1" HEIGHT="1"></TD>
                    </TR>
                  </TABLE>
                  <TABLE WIDTH="340" BORDER="0" CELLSPACING="0" CELLPADDING="0">
                    <TR> 
                      <TD BGCOLOR="#FFFFFF" WIDTH="1"><IMG SRC="../img/general/spacer.gif" WIDTH="1" HEIGHT="1"></TD>
                      <TD WIDTH="340"> 
                        <TABLE WIDTH="100%" BORDER="0" CELLSPACING="1" CELLPADDING="1">
                          <TR> 
                            <TD WIDTH="200" ALIGN="center" BGCOLOR="#000000">Motivo</TD>
                            <TD ALIGN="center" WIDTH="70" BGCOLOR="#000000">Partidos</TD>
                            <TD WIDTH="70" ALIGN="center" BGCOLOR="#000000">Goles</TD>
                          </TR>
                          <? 
	$totalp = 0;
	$totalg = 0;
	$zona = mysql_query("SELECT * from partidos_campeonato WHERE zona='intenacional'");
	while($row=mysql_fetch_object($zona)){ 
		$part = mysql_query("SELECT * from partidos WHERE campeonato='$row->campeonato'");
		$partidos = mysql_num_rows($part);
		$g = mysql_query("SELECT * from partidos WHERE campeonato='$row->campeonato'");
			$cantidad=0;
			while($gol=mysql_fetch_object($g)){
			$cantidad=$cantidad+$gol->goles;
			}
?> 
                          <TR> 
                            <TD WIDTH="200" ALIGN="center" BGCOLOR="#666666"><A HREF="javascript:openwin('partidos_ow.html?id=<? echo $row->id ?>','Estadística','width=506,height=250,scrollbars=1')"> 
                              <FONT FACE="Ms Sans Serif" SIZE="1" COLOR="#FFFFFF"><? echo $row->campeonato ?> 
                              &nbsp; &gt;&gt; </FONT></A></TD>
                            <TD ALIGN="center" WIDTH="70" BGCOLOR="#666666"><? echo $partidos ?></TD>
                            <TD WIDTH="70" ALIGN="center" BGCOLOR="#666666"><? echo $cantidad ?></TD>
                          </TR>
                          <? 
		$totalp = $totalp+$partidos;
		$totalg = $totalg+$cantidad;
} 
?> 
                          <TR BGCOLOR="#555555"> 
                            <TD WIDTH="200" ALIGN="center"><B>TOTAL</B></TD>
                            <TD ALIGN="center" WIDTH="70"><B><? echo $totalp ?></B></TD>
                            <TD WIDTH="70" ALIGN="center"><B><? echo $totalg ?></B></TD>
                          </TR>
                        </TABLE>
                      </TD>
                      <TD BGCOLOR="#FFFFFF" WIDTH="1"><IMG SRC="../img/general/spacer.gif" WIDTH="1" HEIGHT="1"></TD>
                    </TR>
                  </TABLE>
                  <TABLE WIDTH="340" BORDER="0" CELLSPACING="0" CELLPADDING="0">
                    <TR BGCOLOR="#FFFFFF"> 
                      <TD><IMG SRC="../img/general/spacer.gif" WIDTH="1" HEIGHT="1"></TD>
                    </TR>
                  </TABLE>
                </TD>
              </TR>
            </TABLE>
          </TD>
        </TR>
      </TABLE>
    </TD>
<TD BGCOLOR="#FFFFFF" WIDTH="1" BACKGROUND="../img/general/title_1.gif"><IMG SRC="../img/general/spacer.gif" WIDTH="1" HEIGHT="1"></TD>
              
  </TR>
</TABLE>
<TABLE WIDTH="480" BORDER="0" CELLSPACING="0" CELLPADDING="0" HEIGHT="1">
  <TR> 
    <TD WIDTH="120"><IMG SRC="../img/general/spacer.gif" WIDTH="1" HEIGHT="1"></TD>
    <TD BGCOLOR="#FFFFFF" WIDTH="358"><IMG SRC="../img/general/spacer.gif" WIDTH="1" HEIGHT="1"></TD>
  </TR>
</TABLE>
