 
<TABLE WIDTH="480" BORDER="0" CELLSPACING="0" CELLPADDING="0">
  <TR BGCOLOR="#FFFFFF"> 
    <TD><IMG SRC="../img/general/spacer.gif" WIDTH="1" HEIGHT="1"><IMG SRC="../img/general/spacer.gif" WIDTH="1" HEIGHT="1"></TD>
  </TR>
</TABLE>
<TABLE WIDTH="480" BORDER="0" CELLSPACING="0" CELLPADDING="0" HEIGHT="18">
  <TR> 
    <TD BGCOLOR="#FFFFFF" WIDTH="1"><IMG SRC="../img/general/spacer.gif" WIDTH="1" HEIGHT="1"></TD>
    <TD WIDTH="478" ALIGN="right"><FONT FACE="Verdana, Arial, Helvetica, sans-serif"><B><FONT COLOR="#FFFFFF">Se 
      Dice de Mi </FONT>&nbsp;&nbsp;</B></FONT></TD>
    <TD BGCOLOR="#FFFFFF" WIDTH="1"><IMG SRC="../img/general/spacer.gif" WIDTH="1" HEIGHT="1"></TD>
  </TR>
</TABLE>
<TABLE WIDTH="480" BORDER="0" CELLSPACING="0" CELLPADDING="0">
  <TR BGCOLOR="#FFFFFF"> 
    <TD><IMG SRC="../img/general/spacer.gif" WIDTH="1" HEIGHT="1"><IMG SRC="../img/general/spacer.gif" WIDTH="1" HEIGHT="1"></TD>
  </TR>
</TABLE>
<TABLE WIDTH="480" BORDER="0" CELLSPACING="0" CELLPADDING="0">
  <TR> 
    <TD BGCOLOR="#FFFFFF" WIDTH="1"><IMG SRC="../img/general/spacer.gif" WIDTH="1" HEIGHT="1"></TD>
    <TD WIDTH="478" BGCOLOR="#000000">&nbsp;</TD>
    <TD BGCOLOR="#FFFFFF" WIDTH="1"><IMG SRC="../img/general/spacer.gif" WIDTH="1" HEIGHT="1"></TD>
  </TR>
</TABLE>
<TABLE WIDTH="480" BORDER="0" CELLSPACING="0" CELLPADDING="0">
  <TR BGCOLOR="#FFFFFF"> 
    <TD><IMG SRC="../img/general/spacer.gif" WIDTH="1" HEIGHT="1"><IMG SRC="../img/general/spacer.gif" WIDTH="1" HEIGHT="1"></TD>
  </TR>
</TABLE>
<TABLE WIDTH="480" BORDER="0" CELLSPACING="0" CELLPADDING="0" HEIGHT="20">
  <TR> 
    <TD WIDTH="121" VALIGN="top"> 
      <TABLE WIDTH="121" BORDER="0" CELLSPACING="0" CELLPADDING="0">
        <TR> 
          <TD BGCOLOR="#FFFFFF" WIDTH="1" HEIGHT="355"><IMG SRC="../img/general/spacer.gif" WIDTH="1" HEIGHT="1"></TD>
          <TD HEIGHT="355" VALIGN="top"> 
            <TABLE WIDTH="120" BORDER="0" CELLSPACING="0" CELLPADDING="0">
              <TR BGCOLOR="#666666"> 
                <TD>&nbsp;</TD>
              </TR>
              <TR BGCOLOR="#FFFFFF"> 
                <TD><IMG SRC="../img/general/spacer.gif" WIDTH="1" HEIGHT="1" HSPACE="1"></TD>
              </TR>
              <TR BGCOLOR="#000000"> 
                <TD HEIGHT="80"><IMG SRC="../img/trayectoria/vida1.jpg" WIDTH="120" HEIGHT="80"></TD>
              </TR>
              <TR BGCOLOR="#666666"> 
                <TD HEIGHT="1" WIDTH="1"><IMG SRC="../img/general/spacer.gif" WIDTH="1" HEIGHT="1"></TD>
              </TR>
              <TR BGCOLOR="#000000"> 
                <TD HEIGHT="80"><IMG SRC="../img/trayectoria/vida2.jpg" WIDTH="120" HEIGHT="80"></TD>
              </TR>
              <TR BGCOLOR="#666666"> 
                <TD><IMG SRC="../img/general/spacer.gif" WIDTH="1" HEIGHT="1"></TD>
              </TR>
              <TR BGCOLOR="#000000"> 
                <TD HEIGHT="80"><IMG SRC="../img/trayectoria/vida3.jpg" WIDTH="120" HEIGHT="80"></TD>
              </TR>
              <TR BGCOLOR="#FFFFFF"> 
                <TD><IMG SRC="../img/general/spacer.gif" WIDTH="1" HEIGHT="1" HSPACE="1"></TD>
              </TR>
            </TABLE>
            <? include "menu.inc" ?> </TD>
        </TR>
      </TABLE>
    </TD>
    <TD BGCOLOR="#FFFFFF" WIDTH="1"><IMG SRC="../img/general/spacer.gif" WIDTH="1" HEIGHT="1"></TD>
    <TD WIDTH="357" VALIGN="top"> 
      <TABLE WIDTH="100%" BORDER="0" CELLSPACING="2" CELLPADDING="2">
        <TR> 
          <TD> 
            <P><B>Johan Cruyff </B>(ex jugador de la selecci&oacute;n holandesa, 
              y ex t&eacute;cnico del Barcelona): <BR>
              &quot;tiene cualidades b&aacute;sicas para poder llegar lejos en 
              el f&uacute;tbol. Es un jugador de mucha calidad, de los que siempre 
              ilusiona ver por las cosas que hacen&quot;. </P>
            <P><B>Leonardo Astrada</B> (ex capit&aacute;n y compa&ntilde;ero de 
              Saviola en River):<BR>
              &quot;La gran diferencia con el equipo anterior es que somos m&aacute;s 
              contundentes... Aimar y Saviola atraviesan por un momento espectacular 
              junto con Angel, son un peligro constante&quot;.<BR>
              <BR>
              <B>Guillermo Barros Schelotto</B> (delantero de Boca): <BR>
              &quot;Saviola es desequilibrante. En pocos partidos en primera demostr&oacute; 
              sus condiciones, que mejorar&aacute;n con la experiencia&quot;.<BR>
              <BR>
              <B>Roberto Bonano</B> (arquero de River): <BR>
              &quot;Nos reencontramos con un estilo... Si Saviola y Aimar siguen 
              en este nivel, River ser&aacute; un equipo complicado; definen un 
              partido en pocos minutos&quot;. <BR>
              <B><BR>
              Ram&oacute;n D&iacute;az </B>(ex director t&eacute;cnico de River): 
              <BR>
              &quot;Saviola y Aimar son mejores que Maradona y Yo. Van muy bien 
              encaminados. Son jugadores j&oacute;venes y d&iacute;a tras d&iacute;as 
              los vamos puliendo; son grandes futbolistas&quot;. <BR>
              <BR>
              <B>Jos&eacute; Pekerma</B>n (DT del seleccionado Sub 23): <BR>
              &quot;Es la aparici&oacute;n m&aacute;s importante del f&uacute;tbol 
              argentino de los &uacute;ltimos a&ntilde;os, por encima de las de 
              Aimar y Riquelme. Tiene una velocidad asombrosa en los &uacute;ltimos 
              metros y eso lo hace un jugador distinto&quot;. <BR>
              <BR>
              <B>Oscar Mas</B> (ex jugador de River): <BR>
              &quot;Es el jugador m&aacute;s joven que explot&oacute; en los &uacute;ltimos 
              tiempos y a&uacute;n no alcanz&oacute; su techo&quot;. <BR>
              <BR>
              <B>Walter G&oacute;mez </B>(ex delantero de River): <BR>
              &quot;Ya dej&oacute; de ser promesa; es una realidad. Todav&iacute;a 
              puede dar mucho m&aacute;s&quot;. <BR>
              <BR>
              <B>Diego Maradona: </B><BR>
              &quot;Es un fen&oacute;meno. En la cancha parece que anduviera en 
              el aire. Ojal&aacute; que tenga m&aacute;s suerte que yo, y eso 
              que yo tuve bastante&quot;. <BR>
              <BR>
              <B>Sven Goran Eriksson</B> (DT de Lazio): <BR>
              &quot;&iexcl;Qu&eacute; b&aacute;rbaro ese petisito! &iexcl;C&oacute;mo 
              se mueve en la cancha! Se ve la clase que tiene en el toque y el 
              trato que le da a la pelota&quot;. <BR>
              <BR>
              <B>Gustavo Lombardi</B> (defensor de River): <BR>
              &quot;En las pr&aacute;cticas no lo marcamos. Lo tenemos entre algodones 
              para que no se lesione. Es fundamental para nosotros&quot;. <BR>
              <BR>
              <B>Carlos &quot;Puma&quot; Morete</B> (ex jugador de River y de 
              Boca):<BR>
              &quot;Es una ardilla, que se escurre por adentro y por afuera, y 
              te vuelve loco. Parece mentira que teniendo apenas 18 a&ntilde;os, 
              juegue como si tuviera 50 cl&aacute;sicos o 10 a&ntilde;os de carrera&quot;.</P>
            <P><B>Luis Artime</B> (ex jugador de la selecci&oacute;n nacional): 
              <BR>
              Saviola arranca de atr&aacute;s, juega por los laterales, es rapid&iacute;simo... 
              Hay que esperarlo. Pero tiene todas las condiciones para ser un 
              crack.&quot;</P>
            </TD>
        </TR>
      </TABLE>
      <IMG SRC="../img/general/spacer.gif" WIDTH="1" HEIGHT="1"></TD>
<TD BGCOLOR="#FFFFFF" WIDTH="1" BACKGROUND="../img/general/title_1.gif"><IMG SRC="../img/general/spacer.gif" WIDTH="1" HEIGHT="1"></TD>
              
  </TR>
</TABLE>
<TABLE WIDTH="480" BORDER="0" CELLSPACING="0" CELLPADDING="0" HEIGHT="1">
  <TR> 
    <TD WIDTH="120"><IMG SRC="../img/general/spacer.gif" WIDTH="1" HEIGHT="1"></TD>
    <TD BGCOLOR="#FFFFFF" WIDTH="358"><IMG SRC="../img/general/spacer.gif" WIDTH="1" HEIGHT="1"></TD>
  </TR>
</TABLE>
