
<TABLE WIDTH="233" BORDER="0" CELLSPACING="0" CELLPADDING="0">
  <TR> 
    <TD BACKGROUND="../img/general/title_1.gif"><IMG SRC="../img/general/spacer.gif" WIDTH="1" HEIGHT="1"></TD>
    <TD ROWSPAN="11" BACKGROUND="../img/general/title_1.gif" WIDTH="1"><IMG SRC="../img/general/spacer.gif" WIDTH="1" HEIGHT="1"></TD>
    <TD BACKGROUND="../img/general/title_1.gif"><IMG SRC="../img/general/spacer.gif" WIDTH="1" HEIGHT="1"></TD>
  </TR>
  <TR> 
    <TD BGCOLOR="#006600" WIDTH="50" ALIGN="center" BACKGROUND="../img/general/verde.jpg"><FONT COLOR="#FFFFFF">E-Cards</FONT></TD>
    <TD BGCOLOR="#006600" WIDTH="182" ALIGN="center" BACKGROUND="../img/general/verde.jpg"><FONT COLOR="#FFFFFF">Las 
      Postales de Javier</FONT></TD>
  </TR>
  <TR> 
    <TD BACKGROUND="../img/general/title_1.gif" WIDTH="50"><IMG SRC="../img/general/spacer.gif" WIDTH="1" HEIGHT="1"></TD>
    <TD BACKGROUND="../img/general/title_1.gif" WIDTH="182"><IMG SRC="../img/general/spacer.gif" WIDTH="1" HEIGHT="1"></TD>
  </TR>
  <TR> 
    <TD WIDTH="50">&nbsp;</TD>
    <TD WIDTH="182" ALIGN="CENTER"><A HREF="javascript:openwin('../comunidad/e_card.html?card=firma','ecard','width=419,height=340,scrollbars=1')"><FONT COLOR="#FFFFFF">Jsaviola</FONT></A></TD>
  </TR>
  <TR> 
    <TD WIDTH="50"><IMG SRC="../img/general/spacer.gif" WIDTH="1" HEIGHT="1"></TD>
    <TD BACKGROUND="../img/general/title_1.gif" WIDTH="182"><IMG SRC="../img/general/spacer.gif" WIDTH="1" HEIGHT="1"></TD>
  </TR>
  <TR> 
    <TD WIDTH="50">&nbsp;</TD>
    <TD WIDTH="182" ALIGN="CENTER"><A HREF="javascript:openwin('../comunidad/e_card.html?card=felicidades','ecard','width=419,height=340,scrollbars=1')"><FONT COLOR="#FFFFFF">Felicidades</FONT></A></TD>
  </TR>
  <TR> 
    <TD WIDTH="50"><IMG SRC="../img/general/spacer.gif" WIDTH="1" HEIGHT="1"></TD>
    <TD BACKGROUND="../img/general/title_1.gif" WIDTH="182"><IMG SRC="../img/general/spacer.gif" WIDTH="1" HEIGHT="1"></TD>
  </TR>
  <TR> 
    <TD WIDTH="50">&nbsp;</TD>
    <TD WIDTH="182" ALIGN="CENTER"><A HREF="javascript:openwin('../comunidad/e_card.html?card=festejemos','ecard','width=419,height=340,scrollbars=1')"><FONT COLOR="#FFFFFF">Triunfo</FONT></A></TD>
  </TR>
  <TR> 
    <TD WIDTH="50"><IMG SRC="../img/general/spacer.gif" WIDTH="1" HEIGHT="1"></TD>
    <TD BACKGROUND="../img/general/title_1.gif" WIDTH="182"><IMG SRC="../img/general/spacer.gif" WIDTH="1" HEIGHT="1"></TD>
  </TR>
  <TR> 
    <TD WIDTH="50">&nbsp;</TD>
    <TD WIDTH="182" ALIGN="CENTER"><A HREF="javascript:openwin('../comunidad/e_card.html?card=otroidolo','ecard','width=419,height=340,scrollbars=1')"><FONT COLOR="#FFFFFF">&Iacute;dolo</FONT></A><A HREF="javascript:openwin('../comunidad/e_card.html?card=festejemos','ecard','width=419,height=340,scrollbars=1')"></A></TD>
  </TR>
  <TR> 
    <TD WIDTH="50"><IMG SRC="../img/general/spacer.gif" WIDTH="1" HEIGHT="1"></TD>
    <TD BACKGROUND="../img/general/title_1.gif" WIDTH="182"><IMG SRC="../img/general/spacer.gif" WIDTH="1" HEIGHT="1"></TD>
  </TR>
</TABLE>
<BR>
